# Based on @blaenk/dots: https://github.com/blaenk/dots/
# Path to my_dots
#
if [ "$(uname -s)" = "Darwin" ]; then
	READLINK=greadlink
else
	READLINK=readlink
fi

DOTSPATH="$(cd $(dirname $(dirname $($READLINK -f ${(%):-%N}))); pwd)"

autoload -U compinit promptinit colors select-word-style
select-word-style bash
compinit -i
promptinit
colors

#history
setopt hist_ignore_space
setopt append_history
setopt hist_ignore_dups

# env vars
export EDITOR=vim
export VISUAL=vim

source $DOTSPATH/zsh/antigen/antigen.zsh

antigen bundles <<EOBUNDLES
  zsh-users/zsh-syntax-highlighting
	zsh-users/zsh-completions src
EOBUNDLES

antigen apply

# strict control over source order
sources=(
	'path'
	'vcsinfo'
	'prompt'
	'completions'
	'highlight'
	'functions'
)

for src in $sources; do
  source $DOTSPATH/zsh/zsh/$src.zsh
done

if [[ -e $DOTSPATH/zsh/zsh/custom.zsh ]]; then
  source $DOTSPATH/zsh/zsh/custom.zsh
fi
